permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  network_key: GENERATE
homeassistant:
  discovery_topic: 'homeassistant'
  status_topic: 'homeassistant/status'